In [1]:
import requests
import tempfile
import pandas as pd
import polars as pl
from pycaret.regression import *
import os
from google.cloud import storage

In [2]:

# Set the path to your service account key file
key_file = "/workspace/Ravikumar/healthy-genre-391115-f36176b04acf.json"

# Set the environment variable for the key file
os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = key_file

# Create a client using the provided credentials
client = storage.Client()

# Specify the GCS URI for the model
gcs_uri = 'gs://githubml_models/ipl_models/ipl_pycaret.pkl'

# Get the bucket and blob names from the GCS URI
bucket_name, blob_name = gcs_uri[5:].split("/", 1)
# Get the bucket
bucket = client.get_bucket(bucket_name)

# Get the blob
blob = bucket.blob(blob_name)

# Download the model file as bytes
model_data = blob.download_as_bytes()
# Create the file.
with tempfile.NamedTemporaryFile(suffix='.pkl', delete=False) as temp_file:
    # Write the model data to the file.
    temp_file.write(model_data)
    # Load the model from the file.
    model = load_model(temp_file.name[:-4])  # Remove the ".pkl" extension

# Close the file.
temp_file.close()

# Now you can use the model for predictions or other tasks

Transformation Pipeline and Model Successfully Loaded

In [3]:
deliveries=pd.read_csv("ipl_final_data.csv",index_col=0)
deliveries

,inning,batting_team_Chennai Super Kings,batting_team_Delhi Capitals,batting_team_Gujarat Lions,batting_team_Kings XI Punjab,batting_team_Kolkata Knight Riders,batting_team_Mumbai Indians,batting_team_Pune Warriors,batting_team_Rajasthan Royals,batting_team_Royal Challengers Bangalore,...,toss_winner_Mumbai Indians,toss_winner_Pune Warriors,toss_winner_Rajasthan Royals,toss_winner_Royal Challengers Bangalore,toss_winner_Sunrisers Hyderabad,toss_decision,balls,current_runs,wickets,current_run_rate
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,1,6.1,60,1,8.571429
1,1,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,1,6.2,60,1,8.571429
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,1,6.3,61,1,8.714286
3,1,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,1,6.4,62,1,8.857143
4,1,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,1,6.5,63,1,9.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88172,2,1,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,19.2,152,5,7.600000
88173,2,1,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,19.3,154,5,7.700000
88174,2,1,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,19.4,155,6,7.750000
88175,2,1,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,19.5,157,6,7.850000
88176,2,1,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,19.6,157,7,7.850000

In [4]:
t1=deliveries.drop("final_runs",axis=1).iloc[1:2]
t1

,inning,batting_team_Chennai Super Kings,batting_team_Delhi Capitals,batting_team_Gujarat Lions,batting_team_Kings XI Punjab,batting_team_Kolkata Knight Riders,batting_team_Mumbai Indians,batting_team_Pune Warriors,batting_team_Rajasthan Royals,batting_team_Royal Challengers Bangalore,...,toss_winner_Mumbai Indians,toss_winner_Pune Warriors,toss_winner_Rajasthan Royals,toss_winner_Royal Challengers Bangalore,toss_winner_Sunrisers Hyderabad,toss_decision,balls,current_runs,wickets,current_run_rate
1,1,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,1,6.2,60,1,8.571429

In [5]:
l=t1.to_dict()
l=l.keys()
l

dict_keys(['inning', 'batting_team_Chennai Super Kings', 'batting_team_Delhi Capitals', 'batting_team_Gujarat Lions', 'batting_team_Kings XI Punjab', 'batting_team_Kolkata Knight Riders', 'batting_team_Mumbai Indians', 'batting_team_Pune Warriors', 'batting_team_Rajasthan Royals', 'batting_team_Royal Challengers Bangalore', 'batting_team_Sunrisers Hyderabad', 'bowling_team_Chennai Super Kings', 'bowling_team_Delhi Capitals', 'bowling_team_Gujarat Lions', 'bowling_team_Kings XI Punjab', 'bowling_team_Kolkata Knight Riders', 'bowling_team_Mumbai Indians', 'bowling_team_Pune Warriors', 'bowling_team_Rajasthan Royals', 'bowling_team_Royal Challengers Bangalore', 'bowling_team_Sunrisers Hyderabad', 'city_Ahmedabad', 'city_Bangalore', 'city_Chandigarh', 'city_Chennai', 'city_Delhi', 'city_Dharamsala', 'city_Hyderabad', 'city_Jaipur', 'city_Kolkata', 'city_Mohali', 'city_Mumbai', 'city_Pune', 'toss_winner_Chennai Super Kings', 'toss_winner_Delhi Capitals', 'toss_winner_Gujarat Lions', 'toss_winner_Kings XI Punjab', 'toss_winner_Kolkata Knight Riders', 'toss_winner_Mumbai Indians', 'toss_winner_Pune Warriors', 'toss_winner_Rajasthan Royals', 'toss_winner_Royal Challengers Bangalore', 'toss_winner_Sunrisers Hyderabad', 'toss_decision', 'balls', 'current_runs', 'wickets', 'current_run_rate'])

In [6]:
X=deliveries.drop("final_runs",axis=1)
Y=deliveries["final_runs"]

In [11]:
t2=[1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 12, 112, 3, 9.333333333333334]

In [12]:
input = {k: {1: v} for k, v in zip(l,t2)}
input

{'inning': {1: 1},
 'batting_team_Chennai Super Kings': {1: 1},
 'batting_team_Delhi Capitals': {1: 0},
 'batting_team_Gujarat Lions': {1: 0},
 'batting_team_Kings XI Punjab': {1: 0},
 'batting_team_Kolkata Knight Riders': {1: 0},
 'batting_team_Mumbai Indians': {1: 0},
 'batting_team_Pune Warriors': {1: 0},
 'batting_team_Rajasthan Royals': {1: 0},
 'batting_team_Royal Challengers Bangalore': {1: 0},
 'batting_team_Sunrisers Hyderabad': {1: 0},
 'bowling_team_Chennai Super Kings': {1: 0},
 'bowling_team_Delhi Capitals': {1: 1},
 'bowling_team_Gujarat Lions': {1: 0},
 'bowling_team_Kings XI Punjab': {1: 0},
 'bowling_team_Kolkata Knight Riders': {1: 0},
 'bowling_team_Mumbai Indians': {1: 0},
 'bowling_team_Pune Warriors': {1: 0},
 'bowling_team_Rajasthan Royals': {1: 0},
 'bowling_team_Royal Challengers Bangalore': {1: 0},
 'bowling_team_Sunrisers Hyderabad': {1: 0},
 'city_Ahmedabad': {1: 0},
 'city_Bangalore': {1: 0},
 'city_Chandigarh': {1: 0},
 'city_Chennai': {1: 0},
 'city_Delhi': {1: 1},
 'city_Dharamsala': {1: 0},
 'city_Hyderabad': {1: 0},
 'city_Jaipur': {1: 0},
 'city_Kolkata': {1: 0},
 'city_Mohali': {1: 0},
 'city_Mumbai': {1: 0},
 'city_Pune': {1: 0},
 'toss_winner_Chennai Super Kings': {1: 1},
 'toss_winner_Delhi Capitals': {1: 0},
 'toss_winner_Gujarat Lions': {1: 0},
 'toss_winner_Kings XI Punjab': {1: 0},
 'toss_winner_Kolkata Knight Riders': {1: 0},
 'toss_winner_Mumbai Indians': {1: 0},
 'toss_winner_Pune Warriors': {1: 0},
 'toss_winner_Rajasthan Royals': {1: 0},
 'toss_winner_Royal Challengers Bangalore': {1: 0},
 'toss_winner_Sunrisers Hyderabad': {1: 0},
 'toss_decision': {1: 1},
 'balls': {1: 12},
 'current_runs': {1: 112},
 'wickets': {1: 3},
 'current_run_rate': {1: 9.333333333333334}}

In [13]:
model.predict(input)

array([206.36])

In [14]:
requests.get("https://storage.googleapis.com/github_ml_models/ipl/ipl_pycaret.pkl")